// cefas gRPC service definition.
//
// Wire format is independent of any third-party item store; the shape
// mirrors DynamoDB only as far as it makes ergonomic sense. Streaming
// reads (Query / Scan / SpatialQuery) keep server memory bounded for
// large result sets.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: cefas.proto

package cefaspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cefas_CreateTable_FullMethodName        = "/cefas.v1.Cefas/CreateTable"
	Cefas_DescribeTable_FullMethodName      = "/cefas.v1.Cefas/DescribeTable"
	Cefas_ListTables_FullMethodName         = "/cefas.v1.Cefas/ListTables"
	Cefas_DropTable_FullMethodName          = "/cefas.v1.Cefas/DropTable"
	Cefas_UpdateTimeToLive_FullMethodName   = "/cefas.v1.Cefas/UpdateTimeToLive"
	Cefas_DescribeTimeToLive_FullMethodName = "/cefas.v1.Cefas/DescribeTimeToLive"
	Cefas_PutItem_FullMethodName            = "/cefas.v1.Cefas/PutItem"
	Cefas_GetItem_FullMethodName            = "/cefas.v1.Cefas/GetItem"
	Cefas_UpdateItem_FullMethodName         = "/cefas.v1.Cefas/UpdateItem"
	Cefas_DeleteItem_FullMethodName         = "/cefas.v1.Cefas/DeleteItem"
	Cefas_BatchWriteItem_FullMethodName     = "/cefas.v1.Cefas/BatchWriteItem"
	Cefas_BatchGetItem_FullMethodName       = "/cefas.v1.Cefas/BatchGetItem"
	Cefas_Query_FullMethodName              = "/cefas.v1.Cefas/Query"
	Cefas_Scan_FullMethodName               = "/cefas.v1.Cefas/Scan"
	Cefas_SpatialQuery_FullMethodName       = "/cefas.v1.Cefas/SpatialQuery"
	Cefas_Sql_FullMethodName                = "/cefas.v1.Cefas/Sql"
	Cefas_ClusterStatus_FullMethodName      = "/cefas.v1.Cefas/ClusterStatus"
	Cefas_AddVoter_FullMethodName           = "/cefas.v1.Cefas/AddVoter"
	Cefas_RemoveServer_FullMethodName       = "/cefas.v1.Cefas/RemoveServer"
	Cefas_StreamChanges_FullMethodName      = "/cefas.v1.Cefas/StreamChanges"
	Cefas_ListSnapshots_FullMethodName      = "/cefas.v1.Cefas/ListSnapshots"
)

// CefasClient is the client API for Cefas service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CefasClient interface {
	// Schema management.
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error)
	DescribeTable(ctx context.Context, in *DescribeTableRequest, opts ...grpc.CallOption) (*DescribeTableResponse, error)
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error)
	// TTL configuration. The reaper already honours TableDescriptor.TTLAttribute;
	// these RPCs only mutate the catalog entry.
	UpdateTimeToLive(ctx context.Context, in *UpdateTimeToLiveRequest, opts ...grpc.CallOption) (*UpdateTimeToLiveResponse, error)
	DescribeTimeToLive(ctx context.Context, in *DescribeTimeToLiveRequest, opts ...grpc.CallOption) (*DescribeTimeToLiveResponse, error)
	// Item operations.
	PutItem(ctx context.Context, in *PutItemRequest, opts ...grpc.CallOption) (*PutItemResponse, error)
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error)
	// Bulk operations.
	BatchWriteItem(ctx context.Context, in *BatchWriteItemRequest, opts ...grpc.CallOption) (*BatchWriteItemResponse, error)
	BatchGetItem(ctx context.Context, in *BatchGetItemRequest, opts ...grpc.CallOption) (*BatchGetItemResponse, error)
	// Query and scan stream rows so the server never materialises an
	// unbounded result set in memory.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Item], error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Item], error)
	SpatialQuery(ctx context.Context, in *SpatialQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Item], error)
	// SQL surface — single statement per call. Affected_rows is set for
	// DDL/DML; rows is set for SELECT.
	Sql(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*SqlResponse, error)
	// Cluster surface (no-ops in single-node mode).
	ClusterStatus(ctx context.Context, in *ClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error)
	AddVoter(ctx context.Context, in *AddVoterRequest, opts ...grpc.CallOption) (*AddVoterResponse, error)
	RemoveServer(ctx context.Context, in *RemoveServerRequest, opts ...grpc.CallOption) (*RemoveServerResponse, error)
	// Change Data Capture stream. Subscribers receive every committed
	// write in raft log order. Slow consumers may miss events when their
	// server-side ring buffer fills; at-least-once-in-order for live
	// consumers.
	StreamChanges(ctx context.Context, in *StreamChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error)
	// Snapshot administration (PITR foundation).
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
}

type cefasClient struct {
	cc grpc.ClientConnInterface
}

func NewCefasClient(cc grpc.ClientConnInterface) CefasClient {
	return &cefasClient{cc}
}

func (c *cefasClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, Cefas_CreateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) DescribeTable(ctx context.Context, in *DescribeTableRequest, opts ...grpc.CallOption) (*DescribeTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeTableResponse)
	err := c.cc.Invoke(ctx, Cefas_DescribeTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTablesResponse)
	err := c.cc.Invoke(ctx, Cefas_ListTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropTableResponse)
	err := c.cc.Invoke(ctx, Cefas_DropTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) UpdateTimeToLive(ctx context.Context, in *UpdateTimeToLiveRequest, opts ...grpc.CallOption) (*UpdateTimeToLiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTimeToLiveResponse)
	err := c.cc.Invoke(ctx, Cefas_UpdateTimeToLive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) DescribeTimeToLive(ctx context.Context, in *DescribeTimeToLiveRequest, opts ...grpc.CallOption) (*DescribeTimeToLiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeTimeToLiveResponse)
	err := c.cc.Invoke(ctx, Cefas_DescribeTimeToLive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) PutItem(ctx context.Context, in *PutItemRequest, opts ...grpc.CallOption) (*PutItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutItemResponse)
	err := c.cc.Invoke(ctx, Cefas_PutItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, Cefas_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateItemResponse)
	err := c.cc.Invoke(ctx, Cefas_UpdateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteItemResponse)
	err := c.cc.Invoke(ctx, Cefas_DeleteItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) BatchWriteItem(ctx context.Context, in *BatchWriteItemRequest, opts ...grpc.CallOption) (*BatchWriteItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchWriteItemResponse)
	err := c.cc.Invoke(ctx, Cefas_BatchWriteItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) BatchGetItem(ctx context.Context, in *BatchGetItemRequest, opts ...grpc.CallOption) (*BatchGetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetItemResponse)
	err := c.cc.Invoke(ctx, Cefas_BatchGetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Item], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cefas_ServiceDesc.Streams[0], Cefas_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, Item]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cefas_QueryClient = grpc.ServerStreamingClient[Item]

func (c *cefasClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Item], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cefas_ServiceDesc.Streams[1], Cefas_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, Item]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cefas_ScanClient = grpc.ServerStreamingClient[Item]

func (c *cefasClient) SpatialQuery(ctx context.Context, in *SpatialQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Item], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cefas_ServiceDesc.Streams[2], Cefas_SpatialQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SpatialQueryRequest, Item]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cefas_SpatialQueryClient = grpc.ServerStreamingClient[Item]

func (c *cefasClient) Sql(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*SqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SqlResponse)
	err := c.cc.Invoke(ctx, Cefas_Sql_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) ClusterStatus(ctx context.Context, in *ClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatusResponse)
	err := c.cc.Invoke(ctx, Cefas_ClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) AddVoter(ctx context.Context, in *AddVoterRequest, opts ...grpc.CallOption) (*AddVoterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVoterResponse)
	err := c.cc.Invoke(ctx, Cefas_AddVoter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) RemoveServer(ctx context.Context, in *RemoveServerRequest, opts ...grpc.CallOption) (*RemoveServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveServerResponse)
	err := c.cc.Invoke(ctx, Cefas_RemoveServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cefasClient) StreamChanges(ctx context.Context, in *StreamChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cefas_ServiceDesc.Streams[3], Cefas_StreamChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChangesRequest, ChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cefas_StreamChangesClient = grpc.ServerStreamingClient[ChangeEvent]

func (c *cefasClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, Cefas_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CefasServer is the server API for Cefas service.
// All implementations must embed UnimplementedCefasServer
// for forward compatibility.
type CefasServer interface {
	// Schema management.
	CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	DescribeTable(context.Context, *DescribeTableRequest) (*DescribeTableResponse, error)
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error)
	// TTL configuration. The reaper already honours TableDescriptor.TTLAttribute;
	// these RPCs only mutate the catalog entry.
	UpdateTimeToLive(context.Context, *UpdateTimeToLiveRequest) (*UpdateTimeToLiveResponse, error)
	DescribeTimeToLive(context.Context, *DescribeTimeToLiveRequest) (*DescribeTimeToLiveResponse, error)
	// Item operations.
	PutItem(context.Context, *PutItemRequest) (*PutItemResponse, error)
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	UpdateItem(context.Context, *UpdateItemRequest) (*UpdateItemResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error)
	// Bulk operations.
	BatchWriteItem(context.Context, *BatchWriteItemRequest) (*BatchWriteItemResponse, error)
	BatchGetItem(context.Context, *BatchGetItemRequest) (*BatchGetItemResponse, error)
	// Query and scan stream rows so the server never materialises an
	// unbounded result set in memory.
	Query(*QueryRequest, grpc.ServerStreamingServer[Item]) error
	Scan(*ScanRequest, grpc.ServerStreamingServer[Item]) error
	SpatialQuery(*SpatialQueryRequest, grpc.ServerStreamingServer[Item]) error
	// SQL surface — single statement per call. Affected_rows is set for
	// DDL/DML; rows is set for SELECT.
	Sql(context.Context, *SqlRequest) (*SqlResponse, error)
	// Cluster surface (no-ops in single-node mode).
	ClusterStatus(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error)
	AddVoter(context.Context, *AddVoterRequest) (*AddVoterResponse, error)
	RemoveServer(context.Context, *RemoveServerRequest) (*RemoveServerResponse, error)
	// Change Data Capture stream. Subscribers receive every committed
	// write in raft log order. Slow consumers may miss events when their
	// server-side ring buffer fills; at-least-once-in-order for live
	// consumers.
	StreamChanges(*StreamChangesRequest, grpc.ServerStreamingServer[ChangeEvent]) error
	// Snapshot administration (PITR foundation).
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	mustEmbedUnimplementedCefasServer()
}

// UnimplementedCefasServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCefasServer struct{}

func (UnimplementedCefasServer) CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedCefasServer) DescribeTable(context.Context, *DescribeTableRequest) (*DescribeTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeTable not implemented")
}
func (UnimplementedCefasServer) ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTables not implemented")
}
func (UnimplementedCefasServer) DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropTable not implemented")
}
func (UnimplementedCefasServer) UpdateTimeToLive(context.Context, *UpdateTimeToLiveRequest) (*UpdateTimeToLiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTimeToLive not implemented")
}
func (UnimplementedCefasServer) DescribeTimeToLive(context.Context, *DescribeTimeToLiveRequest) (*DescribeTimeToLiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeTimeToLive not implemented")
}
func (UnimplementedCefasServer) PutItem(context.Context, *PutItemRequest) (*PutItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutItem not implemented")
}
func (UnimplementedCefasServer) GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedCefasServer) UpdateItem(context.Context, *UpdateItemRequest) (*UpdateItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItem not implemented")
}
func (UnimplementedCefasServer) DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedCefasServer) BatchWriteItem(context.Context, *BatchWriteItemRequest) (*BatchWriteItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchWriteItem not implemented")
}
func (UnimplementedCefasServer) BatchGetItem(context.Context, *BatchGetItemRequest) (*BatchGetItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetItem not implemented")
}
func (UnimplementedCefasServer) Query(*QueryRequest, grpc.ServerStreamingServer[Item]) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedCefasServer) Scan(*ScanRequest, grpc.ServerStreamingServer[Item]) error {
	return status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedCefasServer) SpatialQuery(*SpatialQueryRequest, grpc.ServerStreamingServer[Item]) error {
	return status.Errorf(codes.Unimplemented, "method SpatialQuery not implemented")
}
func (UnimplementedCefasServer) Sql(context.Context, *SqlRequest) (*SqlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sql not implemented")
}
func (UnimplementedCefasServer) ClusterStatus(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterStatus not implemented")
}
func (UnimplementedCefasServer) AddVoter(context.Context, *AddVoterRequest) (*AddVoterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVoter not implemented")
}
func (UnimplementedCefasServer) RemoveServer(context.Context, *RemoveServerRequest) (*RemoveServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveServer not implemented")
}
func (UnimplementedCefasServer) StreamChanges(*StreamChangesRequest, grpc.ServerStreamingServer[ChangeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamChanges not implemented")
}
func (UnimplementedCefasServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedCefasServer) mustEmbedUnimplementedCefasServer() {}
func (UnimplementedCefasServer) testEmbeddedByValue()               {}

// UnsafeCefasServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CefasServer will
// result in compilation errors.
type UnsafeCefasServer interface {
	mustEmbedUnimplementedCefasServer()
}

func RegisterCefasServer(s grpc.ServiceRegistrar, srv CefasServer) {
	// If the following call pancis, it indicates UnimplementedCefasServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cefas_ServiceDesc, srv)
}

func _Cefas_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_CreateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_DescribeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).DescribeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_DescribeTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).DescribeTable(ctx, req.(*DescribeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_ListTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_DropTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).DropTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_DropTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).DropTable(ctx, req.(*DropTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_UpdateTimeToLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTimeToLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).UpdateTimeToLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_UpdateTimeToLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).UpdateTimeToLive(ctx, req.(*UpdateTimeToLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_DescribeTimeToLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTimeToLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).DescribeTimeToLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_DescribeTimeToLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).DescribeTimeToLive(ctx, req.(*DescribeTimeToLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_PutItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).PutItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_PutItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).PutItem(ctx, req.(*PutItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_UpdateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).UpdateItem(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_DeleteItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_BatchWriteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchWriteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).BatchWriteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_BatchWriteItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).BatchWriteItem(ctx, req.(*BatchWriteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_BatchGetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).BatchGetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_BatchGetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).BatchGetItem(ctx, req.(*BatchGetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CefasServer).Query(m, &grpc.GenericServerStream[QueryRequest, Item]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cefas_QueryServer = grpc.ServerStreamingServer[Item]

func _Cefas_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CefasServer).Scan(m, &grpc.GenericServerStream[ScanRequest, Item]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cefas_ScanServer = grpc.ServerStreamingServer[Item]

func _Cefas_SpatialQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SpatialQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CefasServer).SpatialQuery(m, &grpc.GenericServerStream[SpatialQueryRequest, Item]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cefas_SpatialQueryServer = grpc.ServerStreamingServer[Item]

func _Cefas_Sql_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).Sql(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_Sql_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).Sql(ctx, req.(*SqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_ClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).ClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_ClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).ClusterStatus(ctx, req.(*ClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_AddVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVoterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).AddVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_AddVoter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).AddVoter(ctx, req.(*AddVoterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_RemoveServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).RemoveServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_RemoveServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).RemoveServer(ctx, req.(*RemoveServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cefas_StreamChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CefasServer).StreamChanges(m, &grpc.GenericServerStream[StreamChangesRequest, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cefas_StreamChangesServer = grpc.ServerStreamingServer[ChangeEvent]

func _Cefas_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CefasServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cefas_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CefasServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cefas_ServiceDesc is the grpc.ServiceDesc for Cefas service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cefas_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cefas.v1.Cefas",
	HandlerType: (*CefasServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTable",
			Handler:    _Cefas_CreateTable_Handler,
		},
		{
			MethodName: "DescribeTable",
			Handler:    _Cefas_DescribeTable_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _Cefas_ListTables_Handler,
		},
		{
			MethodName: "DropTable",
			Handler:    _Cefas_DropTable_Handler,
		},
		{
			MethodName: "UpdateTimeToLive",
			Handler:    _Cefas_UpdateTimeToLive_Handler,
		},
		{
			MethodName: "DescribeTimeToLive",
			Handler:    _Cefas_DescribeTimeToLive_Handler,
		},
		{
			MethodName: "PutItem",
			Handler:    _Cefas_PutItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _Cefas_GetItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _Cefas_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _Cefas_DeleteItem_Handler,
		},
		{
			MethodName: "BatchWriteItem",
			Handler:    _Cefas_BatchWriteItem_Handler,
		},
		{
			MethodName: "BatchGetItem",
			Handler:    _Cefas_BatchGetItem_Handler,
		},
		{
			MethodName: "Sql",
			Handler:    _Cefas_Sql_Handler,
		},
		{
			MethodName: "ClusterStatus",
			Handler:    _Cefas_ClusterStatus_Handler,
		},
		{
			MethodName: "AddVoter",
			Handler:    _Cefas_AddVoter_Handler,
		},
		{
			MethodName: "RemoveServer",
			Handler:    _Cefas_RemoveServer_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _Cefas_ListSnapshots_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _Cefas_Query_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Scan",
			Handler:       _Cefas_Scan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SpatialQuery",
			Handler:       _Cefas_SpatialQuery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamChanges",
			Handler:       _Cefas_StreamChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cefas.proto",
}
